service: service-test

provider:
  name: aws
  runtime: nodejs6.10
  region: 'eu-west-1'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
      Resource: "*"

functions:
  app:
    handler: index.handler
    events:
      - http: GET /
      - http: POST /upload
